import { END, Graph, START, StateGraph, StateSchema, type GraphNode } from "@langchain/langgraph";
import z from "zod"
import { cohereModel, geminiModel, mistralModel } from "../config/model.ai.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";
// import {} from "../config/model.ai.js";

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),

    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})

const solutionNode: GraphNode<typeof state> = async (state) => {

    const [geminiRes, cohereRes] = await Promise.all([
        geminiModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: geminiRes.text,
        solution_2: cohereRes.text
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {

    const { problem, solution_1, solution_2 } = state;

    // main judge for evaluating solutions
    const judge = createAgent({
        model: geminiModel,

        responseFormat: providerStrategy(
            z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_reasoning: z.string(),
                solution_2_reasoning: z.string()

            })
        ),

        systemPrompt: `You are a judge tasked with evaluating two solutions generated by AI models. Please provide a score out of 10 for each solution, along with reasoning with the scores.`,
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                    Problem: ${problem},
                    Solution_1: ${solution_1},
                    Solution_2: ${solution_2},
                    Please evaluate solutions and provide scores and reasonings
                `)
        ]
    })

    const { solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning } = judgeResponse.structuredResponse;

    return {
        judge: {
            solution_1_score, 
            solution_2_score, 
            solution_1_reasoning, 
            solution_2_reasoning
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solution_node", solutionNode)
    .addNode("judge_node", judgeNode)

    .addEdge(START, "solution_node")
    .addEdge("solution_node", "judge_node")
    .addEdge("judge_node", END)
    .compile()


async function runGraph(problem: string) {
    
    const result = graph.invoke({
        problem: problem
    })

    return result
}

export default runGraph